config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/signup", to: "home#signup"
  post "/signup", to: "home#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/facebook/callback", to: "sessions#create"
  get "/auth/failure", to: "home#index"
  delete "/logout", to: "sessions#destroy"

  resources :employees, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end
    
    resources :messages, only: [:new, :create, :index]
  end

  resources :chefs, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end

    resources :messages, only: [:new, :create, :index]
  end

  namespace :admins do
    root "home#index"

    get "approval/employee_approve"
    get "approval/chef_approve"

    get "visible/employee_order_notification"
    get "visible/chef_order_notification"
  end

  resources :notifications, only: [:update]

  resources :statuses, except: [:show]

  resources :companies, except: [:show]

  resources :categories
  
  resources :food_stores do
    resources :food_galleries, only: [:new, :create]
  end

  resources :foods

  resources :carts, only: [:edit, :update, :show, :destroy] do
    member do
      get "checkout"
    end

    collection do
      get "history"
      get "recieved"
      get "pending"
    end
  end

  resources :cart_items, except: [:show]

  mount ActionCable.server => "/cable"

end

app/models/employee.rb
class Employee < ApplicationRecord

  has_secure_password
  
  belongs_to :company, optional: true

  has_many :carts,                              dependent: :destroy
  has_many :notifications,  as: :notifiable,    dependent: :destroy
  has_many :messages,       as: :sendable,      dependent: :destroy
  has_many :messages,       as: :recipientable, dependent: :destroy

  before_save { self.name = self.name.to_s.titlecase }
  before_save { self.email = self.email.to_s.downcase }

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,4})\z/i
  validates :email, null: false, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  validate :cannot_approve_without_company, on: :update

  scope :only_approved,  -> { where(approved: true) }
  scope :pending_access, -> { where(approved: nil).where.not(company: nil) }

  def approve_access
    update(approved: true)
  end

  def reject_access
    update(approved: false)
  end

  def cannot_approve_without_company
    if company.nil? && !approved.nil?
      errors[:base] << "The employee does not have any company"
    end
  end

  def update_from_omniauth(auth)
    self.provider = auth.provider
    self.uid = auth.uid
    self.name = auth.info.name
    self.oauth_token = auth.credentials.token
    self.oauth_expires_at = Time.at(auth.credentials.expires_at)
    self.save
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_employee, only: [:show, :edit, :update, :read_all_notifications]
  before_action :authenticate_admin, only: [:approve, :reject, :notification_visible]
  before_action :set_employee, only: [:approve, :reject, :notification_visible]

  def show
    @employee = current_employee
  end

  def edit
    @employee = current_employee
  end

  def update
    @employee = current_employee

    if @employee.company_id.to_s != params[:employee][:company_id]
      flash[:info] = "The updated company access will be approved by the Admin"
      @employee.update(approved: nil)
    end

    if @employee.update(employee_params)
      redirect_to(employee_path(@employee), flash: { success: "Profile information updated!" })
    else
      render "new"
    end
  end

  def approve
    if @employee.approve_access
      Notification.create(notifiable: @employee, content: "You have been approved by the admin")

      redirect_back(fallback_location: admins_root_path, flash: { success: "Employee Access Approved" })
    else
      redirect_back(fallback_location: admins_root_path, flash: { danger: "Employee Access Not Approved" })
    end
  end

  def reject
    if @employee.reject_access
      Notification.create(notifiable: @employee, content: "You have been rejected by the admin")

      redirect_back(fallback_location: admins_root_path, flash: { success: "Employee Access Rejected" })
    else
      redirect_back(fallback_location: admins_root_path, flash: { danger: "Something Went Wrong" })
    end
  end

  def notification_visible
    if @employee.update(order_notification_visible: params[:visible])
      redirect_back(fallback_location: admins_root_path, flash: { success: "Visible status changed" })
    end
  end

  private
    def employee_params
      params.require(:employee).permit(:name, :phone, :company_id)
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
  
  def login_employee(user)
    session[:employee_id] = user.id
  end

  def current_employee
    @current_employee ||= Employee.find(session[:employee_id]) if session[:employee_id]  
  end

  def authenticate_employee
    return unless current_employee.nil?

    redirect_to(login_path, flash: { info: "You have to login first! "})  
  end

  def employee_return_path
    return_path = session[:return_to] || employee_path(session[:employee_id])
  end

end

app/views/employees/_form.html.erb
<%=  form_for(@employee) do |f|%>
  <%= render(partial: "shared/error_messages", locals: { target: @employee }) %>
  
  <div class="form-group">
    <%= f.label :name,  "Your Name " %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Your Name" %>
  </div>

  <div class="form-group">
    <%= f.label :phone, "Phone " %>
    <%= f.text_field :phone, class: "form-control", pattern: "[6-9][0-9]{9}", placeholder: "Enter Phone No." %>
  </div>

  <div class="form-group">
    <%= f.label :company_id, "Company Name : " %>
    <%= f.collection_select(:company_id, Company.all, :id, :name, { selected: @employee.company_id , prompt: "Select a company" }, class: "form-control") %>
  </div>
  
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary mb-2"  %>
  </div>
<% end %>

app/views/employees/_navbar.html.erb
<li class = "nav-item">
  <%= link_to "Home", root_path, class: "nav-link" %>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown">
    Notifications
    <span class = "badge badge-warning" >
      <%= @notifications.unread.count %>
    </span>
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" data-notifications="<%="employee"+current_employee.id.to_s %>" >
    <%= render(partial:"notifications/notification", collection: @notifications.order_desc) %>
  </div>
</li>
<li class = "nav-item">
  <%= link_to("Messages", employee_messages_path(current_employee), class: "nav-link") %>
</li>
<li class = "nav-item">
  <%= link_to("Order Food", foods_path, class: "nav-link") %>
</li>
<li class = "nav-item">
  <%= link_to(cart_path(set_current_cart), class: "nav-link") do %>
    View Cart
    <span class = "badge badge-warning">
      <%= @current_cart.cart_items.count  %>
    </span>
  <% end %>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown">
    Profile
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to(employee_path(@current_employee), class: "dropdown-item") do %>
      <span>Dashboard</span>
    <% end %>
    <%= link_to(history_carts_path, class: "dropdown-item") do %>
      <span>Orders History</span>
    <% end %>
    <%= link_to(edit_employee_path(@current_employee), class: "dropdown-item") do %>
      <span>Edit Profile</span>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to(logout_path, method: :delete, class: "dropdown-item") do %>
      <span>Logout</span>
    <% end %>
  </div>
</li>

app/views/employees/edit.html.erb
<% @page_title = "Edit Your Profile" %>

<%= render(partial: "form") %>

app/views/employees/show.html.erb
<% @page_title = "Profile Dashboard" %>

<script>
  var emp_id = <%= @employee.id %>
  if(App['notify-employee' + emp_id ] == null) {
    
    App['notify-employee' + emp_id ] = App.cable.subscriptions.create(
      { channel: "NotificationsChannel", class: "Employee", id: emp_id },
      {
        connected: function() {
          console.log("connected");
        },

        disconnected: function() {},

        received: function(data) {
          console.log(data["notification"]);
          let a = '[data-notifications = employee'+ emp_id +']';

          current_count1 = $(a).siblings('.dropdown-toggle').children('.badge').html();
          $(a).siblings('.dropdown-toggle').children('.badge').html(parseInt(current_count1)+1);

          $(a).prepend(data["notification"]);

          if(data["notification"].indexOf("approved")!= -1)
          {
            $('#approveEmployee' + emp_id).html("<strong>Approved : </strong><span class = 'text-success'>Approved</span>");
          }
          else if(data["notification"].indexOf("rejected")!= -1)
          {
            $('#approveEmployee' + emp_id ).html("<strong>Approved : </strong><span class = 'text-danger'>Rejected</span>");
          }

        }
      }
    );
    console.log("new employee notification channel");
  }


  if(App['msg-employee'+emp_id] == null)
  {
    App['msg-employee'+emp_id] = App.cable.subscriptions.create(
      { channel: "MessagesChannel", class: "Employee", id: emp_id },
      {
        connected: function() {
          console.log('connected');
        },

        disconnected: function() {},

        received: function(data) {
          console.log(data['message']);
          let employee_div = '[data-messages = Employee'+emp_id+']';
          console.log(employee_div);
          
          $(employee_div).prepend(data['message']);
        }
      }
    );
    console.log("employee msg channel created");
  }

</script>

<% if @employee.name.blank? || @employee.phone.blank? || @employee.company.blank? %>
  <%= link_to("Complete Your Profile", edit_employee_path(@current_employee), class:"btn btn-primary m-5 w-25") %>
<% end %>

<div>
  <div>
    <strong>Name : </strong><span><%= @employee.try(:name) %></span>
  </div>

  <div>
    <strong>E-mail : </strong><span><%= @employee.try(:email) %></span>
  </div>

  <div>
    <strong>Phone : </strong><span><%= @employee.try(:phone) %></span>
  </div>

  <div>
    <strong>Company : </strong>
    
    <% if !@employee.company.blank? %>
      <span><%= @employee.company.try(:name) %></span>
    <% end %>
  </div>

  <div id = "approveEmployee<%= @employee.id %>">
    <strong>Approved : </strong>
    <% if @employee.approved %>
      <span class = "text-success">Approved</span>
    <% elsif @employee.approved.nil? %>
      <span class = "text-info">Pending</span>
    <% else %>
      <span class = "text-danger">Rejected</span>
    <% end %>
  </div>
</div>