config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/signup", to: "home#signup"
  post "/signup", to: "home#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/facebook/callback", to: "sessions#create"
  get "/auth/failure", to: "home#index"
  delete "/logout", to: "sessions#destroy"

  resources :employees, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end
    
    resources :messages, only: [:new, :create, :index]
  end

  resources :chefs, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end

    resources :messages, only: [:new, :create, :index]
  end

  namespace :admins do
    root "home#index"

    get "approval/employee_approve"
    get "approval/chef_approve"

    get "visible/employee_order_notification"
    get "visible/chef_order_notification"
  end

  resources :notifications, only: [:update]

  resources :statuses, except: [:show]

  resources :companies, except: [:show]

  resources :categories
  
  resources :food_stores do
    resources :food_galleries, only: [:new, :create]
  end

  resources :foods

  resources :carts, only: [:edit, :update, :show, :destroy] do
    member do
      get "checkout"
    end

    collection do
      get "history"
      get "recieved"
      get "pending"
    end
  end

  resources :cart_items, except: [:show]

  mount ActionCable.server => "/cable"

end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
  skip_before_action :set_notification_badge
  before_action :authenticate_admin
  
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in?, only:[:signup, :create]

  def index
    @categories = Category.order_by_name.limit(10)
    @food_stores = FoodStore.order_by_name.limit(10)
  end

  def signup
  end

  def create

    if params[:user][:type].present?
      user_class = params[:user][:type]

      if user_class == "Employee"
        user = Employee.new(signup_params)

        if user.save
          session[user_class.downcase.concat("_id").to_sym] = user.id
          redirect_to( employee_path(user.id), flash: { success: "Sign Up successfully"})
        else
          @errors = user.errors.full_messages
          render "signup"
        end
      else
        user = Chef.create(signup_params)
        
        if user.save
          session[user_class.downcase.concat("_id").to_sym] = user.id
          redirect_to( chef_path(user.id), flash: { success: "Sign Up successfully"})
        else
          @errors = user.errors.full_messages
          render "signup"
        end
      end
    else
      flash[:info] = "Please select an option"
      render "new"
    end

  end

  private
    def signup_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/views/home/index.html.erb
<% @page_title = "Home Page"%>

<%= link_to(categories_path, class: "btn btn-warning my-5") do %>
  <h3>View All Categories</h3>
<% end %>

<div class = "row">
  <% @categories.each do |cat| %>
    <div class = "col-md-3 col-sm-12">
      <div class = "card p-2 my-2">
        <div class = "card-title">
          <h3><%= cat.name %></h3>
        </div>
        <div class = "card-body">
          <%= link_to "Browse this category", category_path(cat), class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to(food_stores_path, class: "btn btn-warning my-5") do %>
  <h3>View All Food Stores</h3>
<% end %>

<div class = "row">
  <% @food_stores.each do |store| %>
    <div class = "col-md-3 col-sm-12">
      <div class = "card p-2 my-2">
        <div class = "card-title">
          <h3><%= store.name %></h3>
        </div>
        <div class = "card-body">
          <%= link_to "Browse this Food Store",food_store_path(store), class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/signup.html.erb
<%  @page_title = "Sign Up" %>

<%= form_for(:user) do |f| %>
  <ul class = "list-group">
    <% @errors.try(:each) do |message| %>
      <li class = "list-group-item list-group-item-danger"><%= message %></li>
    <% end %>
  </ul>

  <div class = "form-group">
    <%= f.label :email, "Email "%>
    <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= f.label :password, "Password "%>
    <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :password_confirmation, "Password Confirmation"%>
    <%= f.password_field :password_confirmation, placeholder: "Enter your password again", class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.collection_select(:type, { "Sign Up as Employee": "Employee", "Sign Up as Chef": "Chef" }, :last, :first) %>
  </div>

  <div class = "form-group">
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>

<% end %>