config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/signup", to: "home#signup"
  post "/signup", to: "home#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/facebook/callback", to: "sessions#create"
  get "/auth/failure", to: "home#index"
  delete "/logout", to: "sessions#destroy"

  resources :employees, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end
    
    resources :messages, only: [:new, :create, :index]
  end

  resources :chefs, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end

    resources :messages, only: [:new, :create, :index]
  end

  namespace :admins do
    root "home#index"

    get "approval/employee_approve"
    get "approval/chef_approve"

    get "visible/employee_order_notification"
    get "visible/chef_order_notification"
  end

  resources :notifications, only: [:update]

  resources :statuses, except: [:show]

  resources :companies, except: [:show]

  resources :categories
  
  resources :food_stores do
    resources :food_galleries, only: [:new, :create]
  end

  resources :foods

  resources :carts, only: [:edit, :update, :show, :destroy] do
    member do
      get "checkout"
    end

    collection do
      get "history"
      get "recieved"
      get "pending"
    end
  end

  resources :cart_items, except: [:show]

  mount ActionCable.server => "/cable"

end

app/models/cart.rb
class Cart < ApplicationRecord

  enum priority: [:Low, :High]

  belongs_to :employee
  belongs_to :food_store, optional: true
  belongs_to :status, optional: true
  
  has_many :cart_items, dependent: :destroy
  
  scope :find_by_employee, ->(employee) { where(employee: employee) }
  scope :find_by_foodstore, ->(foodstore) { where(food_store: foodstore) }
  scope :order_placed_desc, -> { where.not(placed_at: nil).order(placed_at: :desc) }
  scope :order_placed_priority_desc, -> { where.not(priority: nil).order(:priority, placed_at: :desc) }

  def checkout_cart
    update(placed_at: Time.now, total_price: self.total)
  end

  def total
    @total = 0
    self.cart_items.each do |item|
      @total += item.quantity * item.food.price
    end
    @total
  end

  def delivered
    update(delivered_at: Time.now)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_employee, only: [:show, :destroy, :checkout, :history]
  before_action(only: [:show, :destroy, :checkout, :history]){ approved(current_employee) }
  before_action :set_current_cart, only: [:show, :destroy, :checkout]
  before_action :authenticate_admin, only: [:pending]
  before_action :authenticate_chef, only: [:recieved]
  before_action :set_cart, only: [:edit, :update]

  def edit
  end

  def update
    if @cart.update(cart_params)

      if current_admin
        redirect_to(pending_carts_path, flash: { success: "Order has been updated" })
      elsif current_chef

        if @cart.status.name == "Delivered"
          @cart.delivered
        end

        if @cart.employee.order_notification_visible
          Notification.create(notifiable: @cart.employee, content: "Your order is #{ @cart.status.name }")
        end

        if current_chef.order_notification_visible
          Notification.create(notifiable: current_chef, content: "Order id #{@cart.id} is #{ @cart.status.name }")
        end

        redirect_to(recieved_carts_path, flash: { success: "Update done" })
      end
    else
      redirect_back(fallback_location: root_path, flash: { danger: "Update cannot be done" })
    end
  end

  def show
  end

  def destroy
    session[:cart_id] = nil
    @current_cart.destroy
    redirect_back(fallback_location: root_path, flash: { info: "All foods deleted" } )
  end

  def checkout
    @current_cart.checkout_cart
    session[:cart_id] = nil
    redirect_to(history_carts_path, flash: { success: "Your order has been placed " })
  end

  def history
    @orders = Cart.includes(:employee, :food_store, { cart_items: :food }, :status).find_by_employee(current_employee).order_placed_desc
  end

  def pending
    @orders = Cart.includes({ employee: :company }, :food_store, :status).order_placed_desc
  end

  def recieved
    @orders = Cart.includes({ employee: :company }, :food_store, { cart_items: :food }, :status).find_by_foodstore(current_chef.food_store).order_placed_priority_desc
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:status_id, :priority)
    end
end

app/helpers/cart_helper.rb
module CartHelper

  def set_current_cart
    
    if !session[:cart_id].nil?
      @current_cart ||= Cart.find(session[:cart_id]) if !session[:cart_id].nil?
    else
      @current_cart = current_employee.carts.create
      session[:cart_id] = @current_cart.id
    end

    @current_cart
  end
  
end

app/views/carts/edit.html.erb
<% @page_title = "Edit Order" %>

<%= form_for(@cart, html: { class: "form-inline m-3" }) do |f| %>
  <%= render(partial: "shared/error_messages", locals: { target: @cart }) %>

  <div>
    <% if current_admin %>
      <%= f.select(:priority, options_for_select(["Low", "High"], select: @cart.status),
      { prompt: "Select a priority" }, { class: "form-control" }) %>
    <% end %>

    <% if current_chef %>
      <%= f.collection_select(:status_id, Status.all, :id, :name,
       { prompt: "Select a Status" }, { class: "form-control", selected: @cart.status, required: true } ) %>
    <% end %>
  </div>

  <div>
    <%= f.submit("Update order", class: "btn btn-primary mx-5") %>
  </div>
<% end %>

<% if current_chef %>
  <%= link_to("Back to recieved order", recieved_carts_path, class: "btn btn-primary") %>
<% end %>

app/views/carts/history.html.erb
<% @page_title = "View Orders" %>

<% if @orders.count!= 0 %>
  <% @orders.each do |order| %>
    <table class = "table mt-3 mb-5">
      <thead>
        <tr class = "table-info">
          <th colspan="4"><%= "Order to : #{ order.food_store.try(:name) }" %></th>
        </tr>
        <tr class = "table-info">
          <th colspan="4"><%= "Placed At : #{ order.placed_at.to_formatted_s(:long) }" %></th>
        </tr>
        <tr>
          <th>Food name</th>
          <th>Quantity</th>
          <th>Extra preferences</th>
          <th>Total price</th>
        </tr>
      </thead>

      <tbody>
        <% order.cart_items.each do |item| %>
          <tr>
            <td><%= item.food.name %></td>
            <td><%= item.quantity %></td>
            <td><%= item.description %></td>
            <td><%= "#{ item.food.price } X #{ item.quantity } = #{ item.food.price*item.quantity }" %></td>
          </td>
        <% end %>
      </tbody>

      <tfoot>
        <tr>
          <th colspan="3">Total : </th>
          <td><%= order.total_price %></th>
        </tr>
        <tr>
          <% if order.status.nil? %>
            <th colspan="4"><%= "Status : Pending" %></th>
          <% else %>
            <th colspan="2"><%= "Status : #{ order.status.name }" %></th>
            <% if !order.delivered_at.nil? %>
              <th colspan="2"><%= "Delivered At : #{ order.delivered_at.to_formatted_s(:long) }" %></th>
            <% else %>
              <th colspan = "2"></th>
            <% end %>
          <% end %>
        </tr>
      </tfoot>
    </table>

  <% end %>
<% else %>
  <div class = "text-info">No pending order</div>
<% end %>

app/views/carts/pending.html.erb
<% @page_title = "Pending Orders" %>

<% if @orders.count!= 0 %>
  <table class = "table mt-3 mb-5">
    <thead>
      <tr>
        <th>Employee Name</th>
        <th>Employee Comapany</th>
        <th>Order to</th>
        <th>Status</th>
        <th>Priority</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.employee.name %></td>
          <td><%= order.employee.company.try(:name) %></td>
          <td><%= order.food_store.try(:name) %></td>

          <% if order.status.nil? %>
            <td><%= "Pending" %></td>
          <% else %>
            <td><%= order.status.name %></td>
          <% end %>

          <% if order.priority.nil? %>
            <td><%= "NA" %></td>
          <% else %>
            <td><%= order.priority %></td>
          <% end %>

          <td><%= link_to("Edit Priority", edit_cart_path(order), class: "btn btn-primary") %><td>
        </tr>
      <% end %>
    </tbody>

  </table>
<% else %>
  <div class = "text-info">No pending order</div>
<% end %>

app/views/carts/recieved.html.erb
<% @page_title = "Recieved Orders" %>

<% if @orders.count!= 0 %>
  <% @orders.each do |order| %>
    <table class = "table mt-3 mb-5">
      <thead>
        <tr class = "table-info">
          <th><%= "Order ID : #{ order.id }" %></th>
          <th><%= "From : #{ order.employee.try(:name) }" %></th>
          <th colspan="2"><%= "Comapany : #{ order.employee.company.try(:name) }" %></th>
        </tr>
        <tr class = "table-info">
          <th colspan="4"><%= "Placed At : #{ order.placed_at.to_formatted_s(:long) }" %></th>
        </tr>
        <tr>
          <th>Food name</th>
          <th>Quantity</th>
          <th>Extra preferences</th>
          <th>Total price</th>
        </tr>
      </thead>

      <tbody>
        <% order.cart_items.each do |item| %>
          <tr>
            <td><%= item.food.name %></td>
            <td><%= item.quantity %></td>
            <td><%= item.description %></td>
            <td><%= "#{ item.food.price } X #{ item.quantity } = #{ item.food.price*item.quantity }" %></td>
          </td>
        <% end %>
      </tbody>

      <tfoot>
        <tr>
          <th colspan="3">Total : </th>
          <td><%= order.total_price %></th>
        </tr>
        <tr>
          <% if order.status.nil? %>
            <th colspan="3"><%= "Status : Pending" %></th>
            <td><%= link_to("Change Order Status", edit_cart_path(order), class: "btn btn-primary") %><td>
          <% else %>
            <th><%= "Status : #{ order.status.name }" %></th>
            <% if !order.delivered_at.nil? %>
              <th colspan="2"><%= "Delivered At : #{ order.delivered_at.to_formatted_s(:long) }" %></th>
            <% else %>
              <th colspan = "2"></th>
              <td><%= link_to("Change Order Status", edit_cart_path(order), class: "btn btn-primary") %><td>
            <% end %>
          <% end %>
        </tr>
      </tfoot>
    </table>

  <% end %>
<% else %>
  <div class = "text-center">No orders placed</div>
<% end %>

app/views/carts/show.html.erb
<% @page_title = "View Cart" %>

<h4 class = "text-secondary my-3"><%= "Order to : #{ @current_cart.food_store.try(:name) }" %></h2>

<table class = "table" >
  <thead>
    <tr>
      <th>Food Name</th>
      <th>Extra prefernce</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @total_price = 0 %>
    <% @current_cart.cart_items.each do |item| %>
      <tr>
        <td><%= item.food.name %></td>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= item.food.price %></td>
        <% @total_price += item.food.price * item.quantity %>
        <td><%= link_to("Edit Item", edit_cart_item_path(item), class: "btn btn-primary") %></td>
        <td><%= link_to("Remove Item", cart_item_path(item), method: :delete, data: { confirm: "Are you sure ?" }, class: "btn btn-danger") %></td>
      </tr>
    <% end %>
    <tr>
      <th colspan = "3">Total </th>
      <th><%= @total_price %></th>
    </tr>    
  </tbody>
</table>

<% if @current_cart.cart_items.count!=0 %>
  <div>
    <%= link_to("Delete all foods", cart_path(@current_cart), method: :delete, class: "btn btn-danger my-2", confirm: "Are you sure ?") %>
  </div>
    
  <div>
    <%= link_to("Checkout foods", checkout_cart_path(@current_cart), class: "btn btn-warning my-2", confirm: "Are you sure ?") %>
  </div>
<% end %>