config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "/signup", to: "home#signup"
  post "/signup", to: "home#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/facebook/callback", to: "sessions#create"
  get "/auth/failure", to: "home#index"
  delete "/logout", to: "sessions#destroy"

  resources :employees, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end
    
    resources :messages, only: [:new, :create, :index]
  end

  resources :chefs, only: [:show, :edit, :update] do
    member do
      put "approve"
      put "reject"
      put "notification_visible"
    end

    resources :messages, only: [:new, :create, :index]
  end

  namespace :admins do
    root "home#index"

    get "approval/employee_approve"
    get "approval/chef_approve"

    get "visible/employee_order_notification"
    get "visible/chef_order_notification"
  end

  resources :notifications, only: [:update]

  resources :statuses, except: [:show]

  resources :companies, except: [:show]

  resources :categories
  
  resources :food_stores do
    resources :food_galleries, only: [:new, :create]
  end

  resources :foods

  resources :carts, only: [:edit, :update, :show, :destroy] do
    member do
      get "checkout"
    end

    collection do
      get "history"
      get "recieved"
      get "pending"
    end
  end

  resources :cart_items, except: [:show]

  mount ActionCable.server => "/cable"

end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :foods, dependent: :nullify

  validates :name, null: false, presence: true, uniqueness: { case_sensitive: false }
  before_save { self.name = self.name.to_s.titlecase}

  scope :order_by_name, -> { order(:name) }
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :set_notification_badge, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_category, only: [:edit, :update, :destroy, :show]
  
  def index
    @categories = Category.order_by_name.paginate(page: params[:page])
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to(categories_path, flash: { success: "New category added" })
    else
      render "new"
    end

  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to(categories_path, flash: { success: "Category updated" })
    else
      render "edit"
    end
  end

  def show
    redirect_to(foods_path(category: @category))
  end
  
  def destroy
    @category.destroy
    redirect_to(categories_path, flash: { info: "Category deleted" })
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end
  
end

app/views/categories/_form.html.erb
<%=  form_for(@category) do |f|%>
  <%= render(partial: "shared/error_messages", locals: { target: @category }) %>
  
  <div class = "form-group form-inline">
    <%= f.label :name,"Category Name", class: "mr-2" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter category name" %>
  </div>

  <div class = "form-group">
    <%= f.submit "Submit", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% @page_title = "Edit Category"%>

<%= render(partial: "form") %>

<div>
  <%= link_to "Back", categories_path, class: "btn btn-primary"%>
</div>

app/views/categories/index.html.erb
<% @page_title = "All Categories" %>

<% if current_admin %>
  <%= link_to "Add New Category", new_category_path, class: "btn btn-primary my-2" %>
<% end %>

<div class = "row my-5">
  <% @categories.each do |cat| %>
    <div class = "col-md-3 col-sm-12">
      <div class = "card m-2 p-2">
        <div class = "card-title">
          <h3><%= cat.name %></h3>
        </div>
        <div class = "card-body">
          <% if current_admin %>
            <%= link_to "Edit", edit_category_path(cat), class: "btn btn-warning" %>
            <%= link_to "Delete", category_path(cat), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning" %>
          <% else %>
            <%= link_to "Browse this category", category_path(cat), class: "btn btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate(@categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, 
  list_classes: %w(pagination justify-content-center)) %>
  
<div>
  <% if current_admin %>
    <%= link_to "Back to homepage", admins_root_path,class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Back to homepage", root_path,class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/new.html.erb
<% @page_title="Insert New Category" %>

<%= render(partial: "form") %>

<div>
  <%= link_to "Back", categories_path, class: "btn btn-primary"%>
</div>